### ISSUE TITLE
Build Error -- CF pages

### ISSUE THREAD

**Issue by sam-shervin** [ComputerSocietyVITC/club-website#20]
00:19:09.619 | 18:49:09 [types] Generated 51ms
-- | --
00:19:09.626 | 18:49:09 [check] Getting diagnostics for Astro files in /opt/buildhome/repo...
00:19:12.333 | src/components/Footer.astro:249:41 - warning ts(6133): 'index' is declared but its value is never read.
00:19:12.333 |  
00:19:12.333 | 249             socialMediaLinks.map((link, index) => (
00:19:12.333 | ~~~~~
00:19:12.334 | src/components/Footer.astro:175:43 - warning ts(6133): 'index' is declared but its value is never read.
00:19:12.334 |  
00:19:12.334 | 175               socialMediaLinks.map((link, index) => (
00:19:12.334 | ~~~~~
00:19:12.334 | src/components/Footer.astro:123:32 - warning ts(6133): 'index' is declared but its value is never read.
00:19:12.334 |  
00:19:12.335 | 123             routes.map((route, index) => (
00:19:12.335 | ~~~~~
00:19:12.335 | src/components/Footer.astro:86:41 - warning ts(6133): 'index' is declared but its value is never read.
00:19:12.335 |  
00:19:12.335 | 86             socialMediaLinks.map((link, index) => (
00:19:12.335 | ~~~~~
00:19:12.335 | src/components/Footer.astro:34:30 - warning ts(6133): 'index' is declared but its value is never read.
00:19:12.335 |  
00:19:12.335 | 34           routes.map((route, index) => (
00:19:12.335 | ~~~~~
00:19:12.335 |  
00:19:12.402 | src/components/HomepageRouter.astro:26:20 - error ts(7053): Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ Team: string; Events: string; Projects: string; Blogs: string; }'.
00:19:12.402 | No index signature with a parameter of type 'string' was found on type '{ Team: string; Events: string; Projects: string; Blogs: string; }'.
00:19:12.403 |  
00:19:12.403 | 26               src={routeIcons[route.title]}
00:19:12.403 | ~~~~~~~~~~~~~~~~~~~~~~~
00:19:12.403 | src/components/HomepageRouter.astro:18:32 - warning ts(6133): 'index' is declared but its value is never read.
00:19:12.403 |  
00:19:12.403 | 18     filteredRoutes.map((route, index) => {
00:19:12.403 | ~~~~~
00:19:12.404 |  
00:19:12.862 | src/pages/team.astro:77:27 - error ts(7006): Parameter 'index' implicitly has an 'any' type.
00:19:12.863 |  
00:19:12.863 | 77     function highlightRow(index) {
00:19:12.863 | ~~~~~
00:19:12.863 | src/pages/team.astro:56:31 - warning ts(6133): 'mem' is declared but its value is never read.
00:19:12.863 |  
00:19:12.864 | 56             .map((teamMember, mem) => (
00:19:12.864 | ~~~
00:19:12.864 | src/pages/team.astro:37:31 - warning ts(6133): 'mem' is declared but its value is never read.
00:19:12.864 |  
00:19:12.864 | 37             .map((teamMember, mem) => (
00:19:12.864 | ~~~
00:19:12.865 | src/pages/team.astro:18:31 - warning ts(6133): 'mem' is declared but its value is never read.
00:19:12.865 |  
00:19:12.865 | 18             .map((teamMember, mem) => (
00:19:12.865 | ~~~
00:19:12.865 | src/pages/team.astro:133:16 - warning ts(6387): The signature '(callback: ((this: MediaQueryList, ev: MediaQueryListEvent) => any) \| null): void' of 'mediaQuery.addListener' is deprecated.
00:19:12.865 |  
00:19:12.865 | 133     mediaQuery.addListener((e) => {
00:19:12.865 | ~~~~~~~~~~~
00:19:12.865 |  
00:19:12.902 | src/pages/gallery/[slug].astro:17:6 - error ts(7053): Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ bitwars: { title: string; description: string; imageUrl: string; galleryLink: string; }; ros: { title: string; description: string; imageUrl: string; galleryLink: string; }; code: { title: string; description: string; imageUrl: string; galleryLink: string; }; ... 12 more ...; carnival: { ...; }; }'.
00:19:12.902 | No index signature with a parameter of type 'string' was found on type '{ bitwars: { title: string; description: string; imageUrl: string; galleryLink: string; }; ros: { title: string; description: string; imageUrl: string; galleryLink: string; }; code: { title: string; description: string; imageUrl: string; galleryLink: string; }; ... 12 more ...; carnival: { ...; }; }'.
00:19:12.902 |  
00:19:12.902 | 17     {eventData[slug].title}
00:19:12.903 | ~~~~~~~~~~~~~~~
00:19:12.903 |  
00:19:12.955 | src/react/Accordion.jsx:1:8 - warning ts(6133): 'React' is declared but its value is never read.
00:19:12.955 |  
00:19:12.955 | 1 import React, { useState } from "react";
00:19:12.956 | ~~~~~
00:19:12.956 |  
00:19:13.274 | src/react/events.jsx:1:8 - warning ts(6133): 'React' is declared but its value is never read.
00:19:13.274 |  
00:19:13.274 | 1 import React, { useState, useEffect } from "react";
00:19:13.275 | ~~~~~
00:19:13.275 |  
00:19:13.401 | src/react/projects.jsx:1:8 - warning ts(6133): 'React' is declared but its value is never read.
00:19:13.401 |  
00:19:13.401 | 1 import React, { useState, useEffect } from "react";
00:19:13.401 | ~~~~~
00:19:13.402 |  
00:19:13.402 | Result (31 files):
00:19:13.402 | - 3 errors
00:19:13.402 | - 0 warnings
00:19:13.402 | - 13 hints
00:19:13.402 |  
00:19:13.443 | Failed: Error while executing user command. Exited with error code: 1
00:19:13.451 | Failed: build command exited with code: 1
00:19:14.340 | Failed: error occurred while running build command

**Comment by sam-shervin** [comment]
generating optimized images
--
01:16:44.995 | [CouldNotTransformImage] Could not transform image `/_astro/comsocLogowhite.Bvc-3ja9.webp`. See the stack trace for more information.
01:16:44.996 | Hint:
01:16:44.996 | This is often caused by a corrupted or malformed image. Re-exporting the image from your image editor may fix this issue.
01:16:44.996 | Error reference:
01:16:44.996 | https://docs.astro.build/en/reference/errors/could-not-transform-image/
01:16:44.996 | Stack trace:
01:16:44.996 | at generateImageInternal (file:///opt/buildhome/repo/node_modules/.pnpm/astro@4.12.2_typescript@5.5.4/node_modules/astro/dist/assets/build/generate.js:131:21)
01:16:44.996 | at async file:///opt/buildhome/repo/node_modules/.pnpm/p-queue@8.0.1/node_modules/p-queue/dist/index.js:187:36
01:16:44.996 | Caused by:
01:16:44.997 | Could not find Sharp. Please install Sharp (`sharp`) manually into your project or migrate to another image service.
01:16:44.997 | at loadSharp (file:///opt/buildhome/repo/dist/chunks/astro/assets-service_BLu2eE4d.mjs:531:11)
01:16:44.997 | at async generateImageInternal (file:///opt/buildhome/repo/node_modules/.pnpm/astro@4.12.2_typescript@5.5.4/node_modules/astro/dist/assets/build/generate.js:125:26)
01:16:44.997 | at async file:///opt/buildhome/repo/node_modules/.pnpm/p-queue@8.0.1/node_modules/p-queue/dist/index.js:187:36
01:16:45.031 | Failed: Error while executing user command. Exited with error code: 1
01:16:45.040 | Failed: build command exited with code: 1
01:16:46.023 | Failed: error occurred while running build command

</pre>

**Comment by sam-shervin** [comment]
@a2ys

**Comment by OneRandom1509** [comment]
#22 final fix
